### PR TITLE
fix: correct word 12 in ZEN (#24)

### PR DESCRIPTION
**Pull request by KhrystynaTkachyk**

### CODE REVIEW

**Comment by mykytapavlov** [comment]
Seems like commit author is missing:
Screenshot 2022-12-01 at 08 21 41

use this command to update your last commit:
`git commit --amend --author="Author Name <email@address.com>" --no-edit`
then use:
`git push -f`  (which means delete commits in my branch on github.com (remote) and replace it by commits in my local branch)

**Comment by KhrystynaTkachyk** [comment]
@mykytapavlov I get the following warning when trying to update user info:
_fatal: --author 'Author Name tkachykhr@gmail.com' is not 'Name <email>' and matches no existing author_
Have I missed sth?

**Comment by KhrystynaTkachyk** [comment]
It seems that I managed to change it now.

**Comment by mykytapavlov** [comment]
Great! But.. Seems somebody merged another [PR](https://github.com/mykytapavlov/python-beginner/pull/31) just a minute ago, which fixes another word on the SAME line. So now, you have a conflict between your branch and main branch. It's happens when 2 people modify the same line in a file.
As you can see there is a message "This branch has conflicts that must be resolved" appeared now.
Changes can't be merged unless conflicts are resolved :(

THE FINAL TASK :)

Please resolve the conflict.
HOWTO:
switch to main branch & pull latest changes

1. `git checkout main`
2. `git pull`

Now you have local main branch up to date. (use "git log -2" to see last 2 commits in main)
So switch back to your branch:
4. `git checkout fix-word-khr` (use "git log -2" to see last 2 commits in fix-word-khr)

Now, time to merge your local fix-word-khr branch with your local main in order to resolve a conflict.
To do so, [watch](https://www.youtube.com/watch?v=xNVM5UxlFSA)
5.1 Notes to the video, that guy uses VS Code instead of PyCharm, but it's not important in our case since we work with a git via terminal as well.
4.2 The guy on video resolves conflict between "my-branch" and "his-branch" (locally). In your case you need to resolve conflict between "fix-word-khr" and "main" (locally).
4.3 In PyCharm you may not see those buttons like "Accept Current Change" on video. But you don't really need buttons. You just need to modify text in the way it will have your change (fix of word 12, I count all of them like words, so my change is 18, but I agree that not all of them are words:D) and my change (fix of "word" 18) as well and commit it.

>>>>>>> -- it's just a visual highlight by git of difference between your branch and "branch you merged to your branch", you don't need to keep it either to keep both versions of this line in that file anymore.
So you just need to remove everything unneeded from the text manually (in the video he uses those "Accept Current Change" buttons to do) so and keep "word 11" and "word 18" corrected and commit it like on video.

Let me know in case of any questions! :D

**Review by mykytapavlov — APPROVED** [review]

**Pull request merged**
