### PR TITLE
fix: correct word 1 in ZEN (#24) and resolved merge conflict with word 3 in ZEN

### PR DESCRIPTION
**Pull request by ehryhorenko**

### CODE REVIEW

**Comment by mykytapavlov** [comment]
@ehryhorenko, by number I mean the actual position of the word in text, please change a commit message 
from 
fix: correct word number in ZEN (#24)
to 
fix: correct word 1 in ZEN (#24)

In order to do so, [read](https://stackoverflow.com/a/179147)

**Comment by mykytapavlov** [comment]
@ehryhorenko Great, please also align PR info above as well (click on edit)

**Comment by ehryhorenko** [comment]
I've edited the PR title. Thanks for the task. It was so exciting!!!

**Comment by mykytapavlov** [comment]
Also, something changed in main branch meanwhile we were discussing your changes.
I believe somebody (me:)) merged another [PR](https://github.com/mykytapavlov/python-beginner/pull/27) which fixes word 3 on the same line as word 1.
So now, you have a conflict between your branch and main branch. It's happens when 2 people modify the same line in a file. 
As you can see there is a message "This branch has conflicts that must be resolved" appeared now.
Changes can't be merged unless conflicts are resolved :(

Please resolve the conflict.
HOWTO:
switch to main branch & pull latest changes
1. git checkout main
2. git pull
Now you have local main branch up to date. (use "git log -2" to see last 2 commits in main)

So switch back to your branch:
3. git checkout fix_N24_correct_word_ZEN (use "git log -2" to see last 2 commits in fix_N24_correct_word_ZEN)

4. Now, time to merge your local fix_N24_correct_word_ZEN branch with your local main in order to resolve a conflict.
To do so, [watch](https://www.youtube.com/watch?v=xNVM5UxlFSA)
4.1 Notes to the video, that guy uses VS Code instead of PyCharm, but it's not important in our case since we work with a git via terminal as well.
4.2 The guy on video resolves conflict between "my-branch" and "his-branch" (locally). In your case you need to resolve conflict between "fix_N24_correct_word_ZEN"  and "main" (locally).
4.3 In PyCharm you may not see those buttons like "Accept Current Change" on video. But you don't really need buttons. You just need to modify text in the way it will have your change (fix of word 1) and my change (fix of word 3) as well and commit it.

Feel free to ask a questions ;)

**Comment by ehryhorenko** [comment]
Hope I did right. It was super interesting. 
I also changed the PR title, should I do that?

**Comment by mykytapavlov** [comment]
@ehryhorenko, almost right from perspective of commits history in your branch now, but not from perspective of the file content itself.
The only think you did wrong, you did't modified file correctly.
Basically here:
Screenshot 2022-11-30 at 12 42 01
File is not aligned automatically. This is actually called merge conflict (when git can't align file automatically) and user needs to decide manually what changes should be kept when you resolve a conflict.
By resolving conflict you say: Ok, I do have latest commits from main in my branch now, my commit history is correct, but I do need to align conflicting line manually:
from:
```
<<<<<<< HEAD
Beautiful is better than ugley.
=======
Butiful is better than ugley.
>>>>>>> main
```
to:
`Beautiful is better than ugley.`


That means what you have in you branch on line one:
```
<<<<<<< HEAD
Beautiful is beter than ugley.
=======
```

That means what you have in MAIN branch on line one:
```
=======
Butiful is better than ugley.
>>>>>>> main
```

`>>>>>>> --` it's just a visual highlight by git of difference between your branch and "branch you merged to your branch", you don't need to keep it either to keep both versions of this line in that file anymore.

So you just need to remove everything unneeded from the text manually and keep word 1 and word 3 corrected and commit it like you did.

So THE FINAL task:
Repeat merge once again, but correctly.

In order to do so, you need to rollback the merge (it's not the same as in that video "how to abort Git merge", because merge is already done and there is nothing to abort).

When you want to reset last commit in your commit history:
1. git reset HEAD~

But because your last commit was a merge commit, you will drop from history in your branch my commits too (which you merged to your branch).
Once you've reset last commit, file will be in state modified (but if you'll be looking in git log -5 after every command you run, you'll see that commit history was changed to the state before you've did the merge). So just rollback this modification of the file itself:
2. git checkout ZEN.md

Now you should be in place when you was before starting resolving merge conflict. You have only your commit in history, but not mines and word 1 is modified only.

Now, step 3 is to repeat merge as you did, but before final commit do not include git helpful information in it (like <<<<<<< and so on).

So just change it like that (where you have both words 1 and 3 fixed) manually:

```txt
Beautiful is better than ugley.
Eksplicit is beter than implisit.
Simpl is beter than compleks.
Compleks is beter than komplicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
```

Let me know in case of any questions.

**Comment by mykytapavlov** [comment]
Well done, glad you took you time to get into this.

**Review by mykytapavlov — APPROVED** [review]

**Pull request merged**
