### PR TITLE
fix: correct words 3 in ZEN (#24)

### PR DESCRIPTION
**Pull request by NataliaZhornyk**
Please review my PR

### CODE REVIEW

**Comment by mykytapavlov** [comment]
Hey, but we have certain rule. `Only one word at a time!`.

Reset your commit to the state it was before you've started working on it and do a single correct commit once again.
In order to do so:
`git log -2` - to see last 2 commits in your branch
`git reset HEAD~` - go back to PRE-LAST commit in your history.
`git checkout ZEN.md` - disregard changes you've made in your LAST commit in the file ZEN.md
`git log -2` - to see last 2 commits in your branch (you should not see your one anymore)
Now you "rolled back" your commit.
Then try again :)

**Comment by mykytapavlov** [comment]
Look also into "Files changed" above and you'll see that you actually modified file in 3 places.

**Comment by NataliaZhornyk** [comment]
@mykytapavlov Please review updated PR

**Comment by mykytapavlov** [comment]
@NataliaZhornyk, this is not going to work.
You see, now you have [3 commits](https://github.com/mykytapavlov/python-beginner/pull/35/commits) now.

In your history you should be on mine commit:
Screenshot 2022-12-02 at 17 09 04

You need to repeat the instructions above until you be on mine commit.

**Comment by mykytapavlov** [comment]
Once you remove all your commits, those changes will be only in your local branch (on your computer). To apply those changes to remote branch  (on github), you need to do:
`git push -f` - which is called force push (by mean, forget what you have on remote, override remote history with my local history in this branch)

**Review by mykytapavlov — APPROVED** [review]

**Comment by mykytapavlov** [comment]
To merge your local `FirstCommit` branch with your local main in order to resolve a conflict:
To do so, [watch](https://www.youtube.com/watch?v=xNVM5UxlFSA)
4.1 Notes to the video, that guy uses VS Code instead of PyCharm, but it's not important in our case since we work with a git via terminal as well.
4.2 The guy on video resolves conflict between "my-branch" and "his-branch" (locally). In your case you need to resolve conflict between "FirstCommit" and "main" (locally).
4.3 In PyCharm you may not see those buttons like "Accept Current Change" on video. But you don't really need buttons. You just need to modify text in the way it will have your change (fix of word 11) and my change (fix of word 13) as well and commit it.

>>>>>>> -- it's just a visual highlight by git of difference between your branch and "branch you merged to your branch", you don't need to keep it either to keep both versions of this line in that file anymore.
So you just need to remove everything unneeded from the text manually (in the video he uses those "Accept Current Change" buttons to do) so and set manually your line to:

**Pull request merged**
