### PR TITLE
feat: creating core items for snake

### PR DESCRIPTION
**Pull request by KhrystynaTkachyk**
tried to implement this in a little bit different way, but seems to be less structured

### CODE REVIEW

**Comment by mykytapavlov** [comment]
Is it your own idea or you googled something? :)

**Comment by mykytapavlov** [comment]
From perspective of complete game, better to kick off from what we have right now, try to extend current logic.

**Comment by KhrystynaTkachyk** [comment]
So, I tried to do this, but now I'm a little bit stuck here :(
In the current state I have no idea how to append my board with snake body and food. 
It also would be perfect to differentiate snake's head as well. I got that the head position should be body position by index [-1], but how this should be tied to snake's body throughout the moving on the board...?

**Comment by mykytapavlov** [comment]
@KhrystynaTkachyk 
I've updated [next task](https://github.com/mykytapavlov/python-beginner/issues/101), so you can try to figure it out in you branch based on what we currently have in [snake.py](https://github.com/mykytapavlov/python-beginner/blob/main/snake/snake.py)

**Comment by KhrystynaTkachyk** [comment]
@mykytapavlov 
Am I moving correct way? Or do I have to make some changes?

**Pull request closed without merging**
