### PR TITLE
fix: correct first word in ZEN (#5)

### PR DESCRIPTION
**Pull request by VikaZinovieva**
Sorry, it's invalid name of first commit, it should be: corrected string in ZEN(#5)
So, in the second commit I leave only one corrected word

### CODE REVIEW

**Comment by mykytapavlov** [comment]
Hey, let's start from what word you actually wanted to modify?
Remember, the task is to modify only one single word, not line.
I do see 2 commits in this pull request

First changes:
from
`Simpl is beter than compleks.`

to
`Simple is better than complex.`

Second 
from
`Simple is better than complex.`
to
`Simple is beter than compleks.`

I believe you fixed all 3 words in that line, but in last minute kept only the fix of word Simple, right?

**Comment by VikaZinovieva** [comment]
Yes, I changed it
Sorry, I'm a little bit inattentive(

**Comment by VikaZinovieva** [comment]
As I understand task is to correct ONLY one word, right?

**Comment by mykytapavlov** [comment]
So the actual problem, is that we do not want to have not needed commits in our history, so it's a bad practice to fix something you've commited by creating a new commit on top of it.

So you have 2 options to fix this:

1. Reset your commits to the state it was before you've started working on it and do a single correct commit once again.
In order to do so:
`git reset HEAD~` - go back to PRE-LAST commit in your history.
`git checkout ZEN.md` - disregard changes you've made in your LAST commit in the file ZEN.md
Now you "rolled back" your second commit.

Do the same for your first commit:
`git reset HEAD~` - go back to PRE-PRE-LAST commit in your history.
`git checkout ZEN.md` - disregard changes you've made in your FIRST commit in the file ZEN.md
Now you "rolled back" your first commit. And your history does not have info about last 2 commits anymore. Fresh start.

2. Group your 2 commits into one. [watch](https://www.youtube.com/watch?v=V5KrD7CmO4o)
 
Please use git log -3 (see last 3 commits in history) in order to understand better what is going on with your history of changes in branch.

**Comment by mykytapavlov** [comment]
I rather recommend not to revert your commits:

`git log -5` to show last 5 commits in your branch
`git reset HEAD~` - go back to PRE-LAST commit in your history.
`git status` check if  ZEN.md is modified
`git checkout ZEN.md` - disregard changes you've made in your LAST commit in the file ZEN.md

repeat unless all your commits are removed AND 
`git status` does NOT highlight that ZEN.md is modified

**Comment by mykytapavlov** [comment]
Ok, great!
Let's also correct your commit message.
From:
`fix: correct first word in ZEN (#5)`
To:
`fix: correct word 11 in ZEN (#24)`  - here #24 means issue number

In order to do so:
`git log -1`  - to see your last commit

then: [read](https://stackoverflow.com/a/179147) (by using this command you actually create new commit in place of your last commit with new author info)

Once commit fixed, and `git log -1` shows correct msg, use:
`git push -f` (which means delete commits in my branch on github.com (remote) and replace it by commits in my local branch)

**Comment by mykytapavlov** [comment]
Great! But.. Seems somebody merged another [PR](https://github.com/mykytapavlov/python-beginner/pull/30) just a minute ago, which fixes another word on the SAME line. So now, you have a conflict between your branch and main branch. It's happens when 2 people modify the same line in a file.
As you can see there is a message "This branch has conflicts that must be resolved" appeared now.
Changes can't be merged unless conflicts are resolved :(

THE FINAL TASK :)

Please resolve the conflict.
HOWTO:
switch to main branch & pull latest changes


1. `git checkout main`
2. `git pull`

Now you have local main branch up to date. (use "git log -2" to see last 2 commits in main)
So switch back to your branch:
3. git checkout first_task (use "git log -2" to see last 2 commits in first_task)

Now, time to merge your local first_task branch with your local main in order to resolve a conflict.
To do so, [watch](https://www.youtube.com/watch?v=xNVM5UxlFSA)
4.1 Notes to the video, that guy uses VS Code instead of PyCharm, but it's not important in our case since we work with a git via terminal as well.
4.2 The guy on video resolves conflict between "my-branch" and "his-branch" (locally). In your case you need to resolve conflict between "first_task" and "main" (locally).
4.3 In PyCharm you may not see those buttons like "Accept Current Change" on video. But you don't really need buttons. You just need to modify text in the way it will have your change (fix of word 11) and my change (fix of word 13) as well and commit it.

5. `>>>>>>> `-- it's just a visual highlight by git of difference between your branch and "branch you merged to your branch", you don't need to keep it either to keep both versions of this line in that file anymore.

So you just need to remove everything unneeded from the text manually (in the video he uses those  "Accept Current Change" buttons to do) so and keep word 11 and word 13 corrected and commit it like on video.

Let me know in case of any questions! :D

**Comment by mykytapavlov** [comment]
This merge should account for fix of word 13.
So commits are merged fine, but the words are not aligned manually correctly.
In this branch:
`Simple is beter than compleks.`
In main:
`Simpl is better than compleks.`

but seems you already got it ;D

**Comment by mykytapavlov** [comment]
Repeat merge once again, but correctly.

In order to do so, you need to rollback the merge (it's not the same as in that video "how to abort Git merge", because merge is already done and there is nothing to abort).

When you want to reset last commit in your commit history:

git reset HEAD~
But because your last commit was a merge commit, you will drop from history in your branch my commits too (which you merged to your branch).
Once you've reset last commit, file will be in state modified (but if you'll be looking in git log -5 after every command you run, you'll see that commit history was changed to the state before you've did the merge). So just rollback this modification of the file itself:
2. git checkout ZEN.md

Now you should be in place when you was before starting resolving merge conflict. You have only your commit in history, but not mines and word 11 is modified only (but 18 is not fixed yet).

Now, step 3 is to repeat merge as you did, but before final commit manually keep 11 and 18 words fixed.

**Comment by mykytapavlov** [comment]
Take into account that in parallel main is updated by PRs of other people, but not your line, at least yet, so hurry! :D

**Comment by mykytapavlov** [comment]
Ahhh, you in danger now, somebody tries to fix your word also!
https://github.com/mykytapavlov/python-beginner/pull/32/commits/bbb087d10e3bbb568c695065117d106c69178a51
you need to be first :)

**Pull request merged**
